//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Home_A_Heaven
{
    using System;
    using System.Collections.Generic;
    
    public partial class Product
    {
        public int Id { get; set; }
        public string Name { get; set; }
        public string Old_Price { get; set; }
        public string New_Price { get; set; }
        public string Discount { get; set; }
        public string Matrial { get; set; }
        public string Color { get; set; }
        public string Height { get; set; }
        public string Discription { get; set; }
        public string Size { get; set; }
        public string Selling { get; set; }
        public System.DateTime InsertDate { get; set; }
        public string Status { get; set; }
        public string Type { get; set; }
        public int CategoryId { get; set; }
        public int SubCategoryId { get; set; }
    }
}
