//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Home_A_Heaven
{
    using System;
    using System.Collections.Generic;
    using System.Web;

    public partial class ProductImage
    {
        public int Id { get; set; }
        public int productId { get; set; }
        public string ImageURL { get; set; }
        public HttpPostedFileBase ImageFile { get; set; }
    }
}
